
version: "3"
services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - 80:80 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    command: ["nginx", "-g", "daemon off;"]  

  hr_f:
    image: ignaciomaylin/mis30web:v1
    container_name: hr_f
    ports:
            - 80:80  

  hr_b:
    image: ignaciomaylin/mis30api:v1
    container_name: hr_b
    ports:
            - 8080:8080