
version: "3"
services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
            - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the Nginx configuration file
    command: ["nginx", "-g", "daemon off;"]  # Run Nginx in the foreground

  gateway2:
    image: nginx:latest
    container_name: gateway2
    ports:
      - 443:443 # Expose port 443 for HTTPS
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf:ro  # Mount the Nginx configuration file
      - /etc/letsencrypt/live/fiesta.hashrate.com.ar/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/fiesta.hashrate.com.ar/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    command: ["nginx", "-g", "daemon off;"]  # Run Nginx in the foreground


  hr_f:
    image: ignaciomaylin/mis30web:v1
    container_name: hr_f
    ports:
            - 81:80  

  hr_b:
    image: ignaciomaylin/mis30api:v1
    container_name: hr_b
    ports:
            - 8080:8080